# Generated by Django 4.1.5 on 2023-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_quantity', models.IntegerField()),
                ('end_quantity', models.IntegerField()),
            ],
        ),
    ]
