# Generated by Django 4.1.5 on 2023-10-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StylePricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('x-small', 'x-small'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('x-large', 'x-large')], max_length=100)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fabrictype')),
                ('quantity_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quantityrange')),
                ('style_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stylecategory')),
            ],
        ),
    ]
