# Generated by Django 4.1.5 on 2023-10-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fabrictype_stylecategory_stylepricepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylepricepoint',
            name='estimated_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='fabric_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='style_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quantityrange',
            unique_together={('start_quantity', 'end_quantity')},
        ),
    ]
