# Generated by Django 4.1.5 on 2023-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stylepricepoint_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylepricepoint',
            name='size',
            field=models.CharField(choices=[('3 sizes (S, M, L)', '3 sizes (S, M, L)'), ('5 sizes (XS, S, M, L, XL)', '5 sizes (XS, S, M, L, XL)')], max_length=100),
        ),
    ]
