# Generated by Django 4.1.5 on 2023-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stylepricepoint_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
