# Generated by Django 4.1.5 on 2023-11-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='model_number',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
