# Generated by Django 4.1.5 on 2023-12-10 04:34

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_style_model_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=main.models.style_image_upload_to),
        ),
        migrations.AddField(
            model_name='style',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='main.stylesource'),
        ),
    ]
