# Generated by Django 4.1.5 on 2023-12-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fabricsource_style_available_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='notes',
            new_name='internal_notes',
        ),
    ]
