# Generated by Django 4.1.5 on 2023-12-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_notes_style_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='minimum_order_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
