# Generated by Django 4.1.5 on 2023-12-13 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_style_minimum_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('main_contact_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('additional_information', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_notes', models.CharField(blank=True, max_length=500)),
                ('styles', models.ManyToManyField(to='main.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
