# Generated by Django 4.1.5 on 2023-12-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clientcompany_city_clientcompany_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
