# Generated by Django 4.1.5 on 2023-12-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_quotationrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_showroom',
            field=models.BooleanField(default=False),
        ),
    ]
