# Generated by Django 4.1.5 on 2023-12-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_style_is_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='fabric_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fabric_source', to='main.fabricsource'),
        ),
        migrations.AlterField(
            model_name='style',
            name='minimum_order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='main.stylesource'),
        ),
    ]
