# Generated by Django 4.1.5 on 2023-12-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clientcompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='fabric_model_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
