# Generated by Django 4.1.5 on 2023-12-15 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_style_fabric_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientcompany'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='style',
            name='fabric_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_source', to='main.fabricsource'),
        ),
        migrations.AlterField(
            model_name='style',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='main.stylesource'),
        ),
    ]
